# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-XtH5pSJW0SATba4KzEm24KFzzN0psJs
"""

itens_mao = ["pano de prato", "copos", "fósforo"]
itens_carrinho = ["copos"]

itens_mao = list(set(itens_mao) - set(itens_carrinho))

print("Itens na mão:", itens_mao)